### ISSUE TITLE
pyreadline compatibility

### ISSUE THREAD

**Issue by rubenhorn** [iamtalhaasghar/yewtube#10]
## Issue / Suggestion
Running `yt` I get this error:
```
> yt
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ruben\.local\bin\yt.exe\__main__.py", line 4, in <module>
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\__init__.py", line 7, in <module>
    from . import init
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\init.py", line 19, in <module>
    import readline
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

## Your Environment
Shell: Microsoft Windows [Version 10.0.19043.1526] (cmd)
```
> pipx --version
1.0.0
```
```
> pipx list
venvs are in C:\Users\Ruben\.local\pipx\venvs
apps are exposed on your $PATH at C:\Users\Ruben\.local\bin
   package yewtube 1.1.4, installed using Python 3.10.2
    - yt.exe
```

**Comment by rachmadaniHaryono** [comment]
@rubenhorn can you try using the setup.py on the pr?

**Comment by iamtalhaasghar** [comment]
Fixed in 0e7ecf1

**Comment by rubenhorn** [comment]
Unfortunately I got another one :/ #16 
Will look more into it myself, but sadly don't have much time atm

**Comment by rubenhorn** [comment]
> Fixed in [0e7ecf1](https://github.com/iamtalhaasghar/yewtube/commit/0e7ecf11b23092b70ad4531ce3dac8ccc4b51bcd)

Doesn't this also have to be updated in the [requirements.txt](https://github.com/iamtalhaasghar/yewtube/blob/master/requirements.txt#L1)?

**Comment by rachmadaniHaryono** [comment]
it should be but i assume pip would prioritize argument on setup.py over requirements.txt

https://github.com/iamtalhaasghar/yewtube/blob/664ccd3d7ea773a122aaa676638375bc58f18909/setup.py#L34-L41

or just put `.` (dot) to avoid duplicate

https://stackoverflow.com/a/49684835

**Comment by iamtalhaasghar** [comment]
revived requirements.txt in ff6e59d75834c61d72ec6bbc92f5eb339cc82607

**Comment by rachmadaniHaryono** [comment]
https://github.com/iamtalhaasghar/yewtube/pull/15#issuecomment-1040226092

	pyreadline is not compatible with linux

	i can't find original pyreadline repo but updated repo also mention that it is not compatible with linux

	https://github.com/pyreadline/pyreadline/blob/4e4b7b468cfdf2dfef8e2c8c695a64e96c514213/setup.py#L18-L19

**Comment by iamtalhaasghar** [comment]
I am using `yewtube` on linux and it is working perfectly fine. We'll see if it breaks at some point in future.
