### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by kiketson** [iamtalhaasghar/yewtube#106]
When I select a video, this is what outputs. Same as in MPS.

 [←] seek [→]       [9] volume [0]      [CTRL-C] return
    [↓] SEEK [↑]       [space] pause

    Ben Böhmer live above Cappadocia in Turkey for Cercle [84:29]
                                                                 [1/25>
Traceback (most recent call last):
  File "/home/pi/.local/bin/yt", line 10, in <module>
    sys.exit(main.main())
  File "/home/pi/.local/bin/mps_youtube/main.py", line 148, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/pi/.local/bin/mps_youtube/main.py", line 65, in matchfunction
    func(*matches)
  File "/home/pi/.local/bin/mps_youtube/commands/play.py", line 100, in play
    play_range(songlist, shuffle, repeat, override)
  File "/home/pi/.local/bin/mps_youtube/player.py", line 49, in play_range
    video, stream = stream_details(song, override=override, softrepeat=softrepeat)
  File "/home/pi/.local/bin/mps_youtube/player.py", line 159, in stream_details
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/home/pi/.local/bin/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/pi/.local/bin/mps_youtube/util.py", line 205, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/pi/.local/bin/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/home/pi/.local/bin/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/pi/.local/bin/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/home/pi/.local/bin/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1672, in _real_extract
    token = video_info.get('token') or video_info.get('account_playback_token')
AttributeError: 'NoneType' object has no attribute 'get'

mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2019.01.17
Python version     : 3.7.3 (default, Oct 31 2022, 14:04:00)
[GCC 8.3.0]
Processor          :
Machine type       : armv7l
Architecture       : 32bit, ELF
Platform           : Linux-5.4.83-v7l+-armv7l-with-debian-10.13
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/pi/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US.UTF-8

**Comment by iamtalhaasghar** [comment]
Can you paste your `set config` output. Which media player are you using `mpv`, `mplayer` or `vlc`?

Edit:
You are using older version of yewtube (formerly mps-youtube). Update to latest version.
