### ISSUE TITLE
Crash during start

### ISSUE THREAD

**Issue by AndreiBiziuk** [iamtalhaasghar/yewtube#24]
## Issue / Suggestion

Yewtube crashes during start

>Traceback (most recent call last):
  File "/home/andrei/.local/bin/yt", line 8, in <module>
    sys.exit(main.main())
  File "/home/andrei/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/main.py", line 124, in main
    playlists.load()
  File "/home/andrei/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/playlists.py", line 28, in load
    g.userpl[m3u[:-4]] = read_m3u(os.path.join(g.PLFOLDER, m3u))
  File "/home/andrei/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/playlists.py", line 72, in read_m3u
    ytid = pafy.extract_video_id(line).strip()
  File "/home/andrei/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/pafy.py", line 139, in extract_video_id
    raise ValueError(err % url)
ValueError: Need 11 character video id or the URL of the video. Got https://www.youtube.com/watch?v=None

## Your Environment

>-> % yt --version
yewtube version    : 2.6.6
yt_dlp version     : 2022.02.04
Python version     : 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.16.9-arch1-1-x86_64-with-glibc2.35
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/andrei/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : ru_RU.UTF-8
env:LANGUAGE       : ru:en_US

**Comment by AndreiBiziuk** [comment]
After manual deleting old playlists from `~/.config/mps_youtube/playlists` everything seems working again.
