### ISSUE TITLE
KeyError: 'format_note' because program does not recognizes links of type "https://manifest.googlevideo.com"

### ISSUE THREAD

**Issue by Thomasorus** [iamtalhaasghar/yewtube#4]
## Issue
Installed yewtube following the guide, from a previous mps-youtube install. When searching for a track, the following problem happens.

Error :
```bash
Search results for lofi
> [youtube] 5qap5aO4i9A: Downloading webpage
[youtube] 5qap5aO4i9A: Downloading android player API JSON
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[youtube] 5qap5aO4i9A: Downloading m3u8 information
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thomasperso/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/streams.py", line 185, in _preload
    streamlist = get(song)
  File "/Users/thomasperso/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/streams.py", line 54, in get
    ps = pafy.get_video_streams(ytid)
  File "/Users/thomasperso/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/pafy.py", line 7, in get_video_streams
    return [i for i in info_dict['formats'] if i['format_note'] != 'storyboard']
  File "/Users/thomasperso/.local/pipx/venvs/yewtube/lib/python3.9/site-packages/mps_youtube/pafy.py", line 7, in <listcomp>
    return [i for i in info_dict['formats'] if i['format_note'] != 'storyboard']
KeyError: 'format_note'
```

## Your Environment

Player used: MPV and VLC, same bug.

Does not work:
```
yewtube version      : 1.0.9
   notes           : released on 28 Jan 2022
youtube-dl version : 2021.12.17
Python version     : 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)]
Processor          : arm
Machine type       : arm64
Architecture       : 64bit,
Platform           : macOS-12.1-arm64-arm-64bit
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /Users/thomasperso/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : fr_FR.UTF-8
```

I have another user on my mac, which also uses yewtube but on an older version.

Works:
```
yewtube version      : 1.0.5
   notes           : released on 17 Jan 2022
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.12.17
Python version     : 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)]
Processor          : arm
Machine type       : arm64
Architecture       : 64bit,
Platform           : macOS-12.1-arm64-arm-64bit
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /Users/thomasig1/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : fr_FR.UTF-8
```

**Comment by iamtalhaasghar** [comment]
@Thomasorus  update instructions can be found [here](https://github.com/iamtalhaasghar/yewtube/blob/develop/README.md#upgrading)

**Comment by Thomasorus** [comment]
Hey @iamtalhaasghar, thank you so much for your hard work. I've updated and the bug is fixed. It seems this update changed something: I only have a list of ten results when doing a search now.

![Capture d’écran 2022-01-28 à 17 24 06](https://user-images.githubusercontent.com/8302525/151583804-40b0b878-c1e4-4209-ad54-58a298fd4239.png)

If you want I can open another issue for this.

**Comment by iamtalhaasghar** [comment]
Yes, sure please create a new issue.
