### ISSUE TITLE
Sign in to confirm your age.

### ISSUE THREAD

**Issue by atomi** [iamtalhaasghar/yewtube#69]
I think this is a PAFY issue 

yt-dlp and mpv work correctly on their own with `--coookies=...`

```
> ERROR: [youtube] redacted: Sign in to confirm your age. This video may be inappropriate for some users.
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 638, in extract
    ie_result = self._real_extract(url)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3331, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1158, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1388, in wrapper
    return func(self, *args, **kwargs)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1458, in __extract_info
    ie_result = ie.extract(url)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 664, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [youtube] redacted: Sign in to confirm your age. This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/atomi/.local/lib/python3.8/site-packages/mps_youtube/streams.py", line 189, in _preload
    streamlist = get(song)
  File "/home/atomi/.local/lib/python3.8/site-packages/mps_youtube/streams.py", line 54, in get
    ps = pafy.get_video_streams(ytid)
  File "/home/atomi/.local/lib/python3.8/site-packages/mps_youtube/pafy.py", line 38, in get_video_streams
    info_dict = ydl.extract_info(ytid, download=False)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1379, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1406, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 938, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/atomi/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 883, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] redacted: Sign in to confirm your age. This video may be inappropriate for some users.
```

➜ mpsyt --version
```
yewtube version    : 2.8.2
yt_dlp version     : 2022.03.08.1
Python version     : 3.8.10 (default, Mar 15 2022, 12:22:08) 
```

**Comment by atomi** [comment]
A new install seems to have solved this.

Sorry for the premature ticket.
