### ISSUE TITLE
locale.Error: Unsupported Locale Setting under Kitty on macOS Monterrey

### ISSUE THREAD

**Issue by bvvt** [iamtalhaasghar/yewtube#85]
I'm receiving the following error log when running yewtube under Kitty on macOS Monterrey, the program runs normally with the native Terminal.app client

```
Traceback (most recent call last):
  File "/Users/redcat/.local/bin/yt", line 5, in <module>
    from mps_youtube import main
  File "/Users/redcat/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/main.py", line 49, in <module>
    locale.setlocale(locale.LC_ALL, "")  # for date formatting
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```
## Your Environment

This is my Enviroment  (running with MPV)

```
yewtube version    : 2.8.4
yt_dlp version     : 2022.07.18
Python version     : 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : macOS-12.4-x86_64-i386-64bit
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /Users/redcat/.config/mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
```

```
 System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

**Comment by rachmadaniHaryono** [comment]
hi, can you try #86 and see if the bugfix pr is working

**Comment by bvvt** [comment]
> hi, can you try #86 and see if the bugfix pr is working

Hey rachmandiHaryono, i tried but 

"Traceback (most recent call last):
  File "/Users/redcat/.local/bin/yt", line 5, in <module>
    from mps_youtube import main
  File "/Users/redcat/.local/pipx/venvs/yewtube/lib/python3.10/site-packages/mps_youtube/main.py", line 38, in <module>
    locale.setlocale(locale.LC_ALL, "")  # for date formatting
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)"

I still get that error.
locale.Error: unsupported locale setting
